site_name: Deploying Apereo CAS 6
site_author: Paul Chauvet
site_description: Guide for deploying Apereo CAS 6 - with LDAP & Delegated Azure Authentication, and Apache Tomcat.
site_url: https://paulchauvet.github.io/deploying-cas/
copyright: Copyright &copy; 2021 Paul Chauvet, State University of New York at New Paltz

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/newpaltz-logo.jpg

extra_css:
  - stylesheets/newpaltz.css


nav:
  - About:
    - About this project: about/about-new-paltz.md
    - About the author: about/author-information.md
    - Architecture/design: about/architecture.md
  - Main: index.md
