site_name: Deploying Apereo CAS 6
site_author: Paul Chauvet
site_description: Guide for deploying Apereo CAS 6 - with LDAP & Delegated Azure Authentication, and Apache Tomcat.
site_url: https://paulchauvet.github.io/deploying-cas/
copyright: Copyright &copy; 2021 Paul Chauvet, State University of New York at New Paltz

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/newpaltz-logo.jpg

extra_css:
  - stylesheets/newpaltz.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight  
  - pymdownx.betterem:
      smart_enable: all

nav:
  - Main: index.md
  - About:
    - About this project: about/about-new-paltz.md
    - About the author: about/author-information.md
    - Architecture/design: about/architecture.md
  - Setting up the Environment:
    - Overview: setting-up-the-environment/overview.md
    - Build Environment: setting-up-the-environment/build-environment.md
    - Tomcat setup via Ansible: setting-up-the-environment/tomcat.md


