site_name: Deploying Apereo CAS 6
site_author: Paul Chauvet
site_description: Guide for deploying Apereo CAS 6 - with LDAP & Delegated Azure Authentication, and Apache Tomcat.
site_url: https://paulchauvet.github.io/deploying-cas/
copyright: Copyright &copy; 2021 Paul Chauvet, State University of New York at New Paltz

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/newpaltz-logo.jpg

extra_css:
  - stylesheets/newpaltz.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight  
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic

nav:
  - Main: index.md
  - About:
    - About SUNY New Paltz: about/about-new-paltz.md
    - About the author: about/author-information.md
    - Architecture/design: about/architecture.md
  - Setting up the Environment:
    - Overview: setting-up-the-environment/overview.md
    - Configure time synchronization: setting-up-the-environment/time-synchronization.md
    - Build Environment: setting-up-the-environment/build-environment.md
    - Tomcat:
      - Tomcat Overview: setting-up-the-environment/tomcat/tomcat-overview.md
      - Install an entropy daemon: setting-up-the-environment/tomcat/entropy-daemon.md
      - Install Java: setting-up-the-environment/tomcat/java.md
      - Install Tomcat: setting-up-the-environment/tomcat/tomcat-install.md
      - Install Tomcat dependencies: setting-up-the-environment/tomcat/tomcat-dependencies.md
      - Organize the installation: setting-up-the-environment/tomcat/tomcat-organize.md
      - Harden the installation: setting-up-the-environment/tomcat/tomcat-harden.md
      - Configure asynchronous request support: setting-up-the-environment/tomcat/asynch-request-support.md
      - Configure X-Forwarded-For header processing: setting-up-the-environment/tomcat/config-x-forwarded.md
      - Tune resource caching settings: setting-up-the-environment/tomcat/resource-caching.md
      - Configure asynchronous logging support: setting-up-the-environment/tomcat/configure-async-logging.md
      - Configure systemd to start tomcat: setting-up-the-environment/tomcat/systemd-service.md
    - Tomcat and Ansible:
      - Ansible and Tomcat - Initial Steps: setting-up-the-environment/tomcat-ansible/tomcat-ansible-overview.md
      - Setup Variables: setting-up-the-environment/tomcat-ansible/variables.md
      - Setup Templates: setting-up-the-environment/tomcat-ansible/templates.md
      - Setup Handlers: setting-up-the-environment/tomcat-ansible/handlers.md      
      - Creating tasks: setting-up-the-environment/tomcat-ansible/tasks.md
      - Running the play: setting-up-the-environment/tomcat-ansible/running-the-play.md
    - Apache HTTPD:
      - Use AJP to communicate with Tomcat: setting-up-the-environment/httpd/ajp-proxy.md
  - Building CAS:
    - Overview: building-cas/overview.md
    - Create Gradle Overlay: building-cas/create-gradle-overlay.md
    - Initial CAS config: building-cas/initial-cas-config.md
    - Configure CAS logs: building-cas/cas-log-config.md
    - Ansible playbook setup: building-cas/ansible-cas.md
  - Service Configuration: 
    - Service Overview: service-config/overview.md
  - Building CAS client:
    - CAS client overview: cas-client/overview.md
    - Configure httpd to use CAS: cas-client/httpd-cas-client.md
    - Test the application: cas-client/test-cas-client.md


      


